### ISSUE TITLE
Some Pages Have Buttom Cut Off

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1065]
Some pages (including the manage programs page and the teacherreg mainpage) have the bottom of cut off.

**Comment by milescalabresi** [comment]
This seems to have resurfaced in NEU's learn page <https://neusplash.learningu.org/learn/index.html>.
![image](https://cloud.githubusercontent.com/assets/5506191/22915359/bc575680-f244-11e6-8b99-4dc242c603d5.png). Could be a result of one of their old template overrides, prior to theme updates. I'll look into it.

**Comment by benjaminjkraft** [comment]
@milescalabresi I think @luac is correct that this means there's an unclosed tag (usually a div).  So if it's on a single page, it's probably just in editable text.  If it's everywhere, a TO is a good place to look.

**Comment by milescalabresi** [comment]
Oh, duh. I forgot to check the editable text 😝 Thank you. In that case, I think this issue is fixed by [this](https://github.com/learning-unlimited/ESP-Website/commit/e6284189f3851976539c1a03498a3f51aa24fa1c), [this](https://github.com/learning-unlimited/ESP-Website/commit/021fecbe7d95c28465cab07f741c2eb60cbe2755), or [this](https://github.com/learning-unlimited/ESP-Website/commit/ac5f88e89bd01b74ad579a4a93ac9ccc4918cb4c). It looks like there is no longer a template issue that is affecting multiple sites/pages, so I'm going to close.
