### ISSUE TITLE
Require that "From" be a valid email in the comm panel

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1094]
Some improvements can be made to the CommPanel form, so that mistakes aren't made:
- Modify the help text for the "From" and "Reply-To" fields, so that it is clear that they must be valid e-mail addresses.
- Add a validator to check that the "From" and "Reply-To" fields, if not blank, must be e-mail addresses.

**Comment by milescalabresi** [comment]
Google's mail filters (by default) warn against phishing when emails are sent through the comm panel. I don't know how other mail clients handle this, but it seems like despite the "this will take X seconds to send so it doesn't get caught by spam filters" is not doing a perfect job. I don't know if that's something we can do much about, but it is a thorn in the side of several chapters.

**Comment by benjaminjkraft** [comment]
I believe we've now fixed the phishing-warning, see #1340; if not, please open a separate issue.

If I'm reading [RFC 822](https://www.ietf.org/rfc/rfc0822.txt) right, the "From" field must also be in the format of a valid email; I think the Chicago email with weird headers that I forwarded to web-team a few months ago is due to the way Exim tries to fix things if it's not.  In any case certainly email clients want it to be in the format of a valid email.

Note that this can be of the form "Arbitrary Name Here <foo@bar.learningu.org>"; it doesn't have to be a bare address.  I somewhat doubt that any email client that can't handle a from field of that form will be fine with a from field that isn't even a valid email.

Also, of course, that doesn't mean it actually has to be a valid email address, although it's probably a good idea in case people reply to it instead of to the reply-to.
