### ISSUE TITLE
Better error reporting for onsite grid

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#114]

**Comment by benjaminjkraft** [comment]
@luac do the onsite grid improvements cover this?

**Comment by luac** [comment]
I don't think I touched anything to do with error reporting. However, it might have been fixed some other time, because in my recent experiences using the onsite grid I've found that it usually does say why a class couldn't be added (although you kind of have to know to look for it in the message area).

**Comment by benjaminjkraft** [comment]
That's what I recall as wel.  Given that this is very vague, I'm going to close it, and if we have a more specific problem/request we can open a new issue.
