### ISSUE TITLE
Line Item Types for SplashInfoModule

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1164]
The lunch selection module does not directly use line item types. `SplashInfo.save()` pulls the lunch costs from a `Tag` (splashinfo_costs), and then creates `Transfer` objects with those costs. Rather than a `Tag`, the costs should come from the associated `LineItemTypes`.

The current accounting system will work here if all lunch options are the same price. To support variable cost lunch options, #1119 will have to also be addressed.

**Comment by pricem** [comment]
Joel is starting to work on this.  The current plan is to do essentially what this ticket says (now that #1119 is done), and just switch SplashInfoForm (used by SplashInfoModule) over to using LineItemOptions.  That's easier said than done; we'll see if it's messy and/or requires thinking about other parts of the code.

For what it's worth, I'm pretty sure this ticket is referring to the SplashInfoModule, and not the StudentLunchSelectionModule.  The latter is for choosing which timeslot to reserve for lunch on your schedule, rather than what kind of food to get (maybe these modules should be merged?).

**Comment by jmoldow** [comment]
> For what it's worth, I'm pretty sure this ticket is referring to the SplashInfoModule, and not the StudentLunchSelectionModule.

Yes, that is what I meant. Thanks for correcting me. I will update the title of the issue.

**Comment by joeleg** [comment]
It seems like there is a lot of overlapping functionality between extracosts and the splashinfomodule and I wonder if we should just repurpose/extend the extracosts module.
