### ISSUE TITLE
Unique e-mail addresses

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#118]
Make it possible to require that each user has a unique e-mail address

**Comment by bhorowitz** [comment]
Is this wanted by any program still?

**Comment by willgearty** [comment]
I think it would definitely help with preventing duplicate accounts (as would #1473).
I think it would also help promote students/parents using the student's email address instead of the parent's email address (we get this a lot at Stanford), since the parents usually want their own Guardian account (Stanford sends almost all emails to both the student and guardian email addresses, but there are definitely times when you only want to email the students).
I guess the only time this would be a problem would be if a student doesn't have an email address?
But is that actually a valid concern at this point?

**Comment by mariolsen0112358** [comment]
MIT Spark in particular sees lots of families who use the same email address for the whole family because they think their 12-year-old is too young for email. And often when kids that age have their own email addresses it's their school emails which tend to block out our emails with their super aggressive filters, and if they change schools and lose access to the accounts it's a mess.

I think the warning that accounts already exist with that email address is good enough for preventing many (but definitely not all) users' multiple accounts, but requiring one account per email would result in many more confused emails to us as people lock themselves out while not doing much to prevent multiple accounts (unless the concern is people deliberately making multiple accounts to try to game the lottery). 

Also, requiring unique emails would make setting up test accounts more annoying.

**Comment by benjaminjkraft** [comment]
Yeah, I think there are much better ways to discourage duplicate accounts -- e.g. by making the UI warning you of it clearer.  I don't know that it would actually make sure the students use their email address -- rather I think they would still use the parents', but then when the parent later wants to sign up now they'll be confused.

**Comment by kkbrum** [comment]
Can I propose that we change the default for the "ask_about_duplicate_accounts" tag to be true, and then mark this issue closed? @willgearty @milescalabresi

**Comment by willgearty** [comment]
I think changing the default for the tag and then doing a little cleanup of the actual UI of the warning would be fine.

**Comment by milescalabresi** [comment]
Seconded^ some UI improvements would be nice :D
