### ISSUE TITLE
CSV dumps of teacher/class data

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1214]
Directors seem to want this fairly often and we tell them to ask a webmin. It would be great to have an automated way to do it, ideally one that's configurable.

**Comment by joeleg** [comment]
Perhaps this feature could benefit from a simple export screen where the user is presented with a mult-select interface to pick and choose from the available list of fields?

**Comment by benjaminjkraft** [comment]
That seems like a fine interface.  If you wanted to make it extra-cool, you could allow also choosing what classes to put in it via the classsearch interface, since often directors want classes that, say, are approved, or unapproved, or whatever, and while that can be done in a spreadsheet it might be convenient to allow doing it in the export, and that shouldn't be too hard.  (It should be fairly simple to make another copy of that search interface on another page, and it will just give you a `QuerySet` of classes. Look at the source or ping me if you have trouble.)

**Comment by joeleg** [comment]
Is there a practical pattern for sharing functionality between modules(such as the classsearch interface), without resorting to copy and paste or a major restructuring of the existing module?

**Comment by benjaminjkraft** [comment]
Put it somewhere that's not a program module.  (For example, on a model, or on a controller, or in some utils file.)  Or, if it's a function or static method, you could just import the other program module.

**Comment by joeleg** [comment]
I will tackle the basic functionality in an initial iteration and here is a simple mockup of the field selection screen, which I am thinking would be the second step of a form wizard:

https://www.evernote.com/shard/s310/sh/d9b523bc-a1a6-45c0-8478-c3db63e422f2/4d98fed7d9793b448a1fd864ceae189f

**Comment by milescalabresi** [comment]
And added request in this vein from Clark, assuming someone is still looking at this ticket:
> In the "All Classes Spreadsheet” from the Printables list, it would be helpful if number of sections was included in the csv.
