### ISSUE TITLE
Availability module involves checking too many boxes

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1258]
It's kind of an annoying UI, and more prone to user error than something nicer. In my ideal world we'd have something that looks like whenisgood.

**Comment by willgearty** [comment]
I was thinking something more like the format of whenisgood.net or when2meet.com would be better (as was maybe suggested by #181).

**Comment by willgearty** [comment]
Here's a mockup of a potential UI change: https://jsfiddle.net/willgearty/de0fdtz1/
It's currently very static since we're only using it for a template override, but it should be fairly easy to implement a generic version.

![image](https://user-images.githubusercontent.com/7232514/28584923-5bda1032-7123-11e7-8179-bfa832aef8c7.png)

**Comment by benjaminjkraft** [comment]
Nice, that looks super cool!
