### ISSUE TITLE
Emails sent from comm panel come from a bad address

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#1340]
The website comm panel does a pretty good job of circumventing spam filters with the exception of when a user changes the "from" field, masking your username@diogenes.learningu.org address in favor of some other email (a director's personal address or a program Gmail, for instance). Thus, it behooves admins to leave this address unmasked.

However, this email address may not be well defined (if one has multiple accounts on different *.learningu.org sites), and even if it is, emails to it are not received by the user's entered email address. Furthermore, there is no bounce error message, which means if anyone sends a message to username@diogenes.learningu.org, there is no way for that person to know that the message will not be received.

Proposed fixes:
(1) Emails sent to the address username@diogenes.learningu.org and/or username@\*.learningu.org should be sent to the email address that the user entered when they created their account.
(2) It would also be nice if emails sent from the comm panel came from username@*.learningu.org rather than username@diogenes.learningu.org so that students/teachers/parents may at least recognize the website.
(3) Ideally, masking the "from" field should not land the message in spam, but this may be out of the scope of this fix.

Thanks to @aseering for the following advice:
- Turn each *.learningu.org into an A record for 64.130.234.178 (domain resolves to this IP (IPv4) address)
- Add an MX record for each *.learningu.org pointing to itself [E-mail to this domain should be delivered to any of the following machines (listed by domain name)]
- Possibly add a DNS record with an SPF string saying that *.learningu.org messages are allowed to come from 64.130.234.178

**Comment by willgearty** [comment]
Hi folks,
I'm coming into this a little late, but I was not previous aware that substituting an outside email (e.g. stanfordesp@gmail.com), would cause emails sent from the comm panel to be marked as spam in people's inboxes.
We've been using stanfordesp@gmail.com for almost all outgoing comm panel messages, and we have noticed that often these emails are flagged for people's spam folders, however I was not aware that these two things were related (my assumption was that the comm panel, under any settings, would just result in a lo of spam flags).
If there was a way to still use this email address, but prevent future spam flags, we would definitely be interested.
I wasn't aware of email forwarding from username@*.learningu.org, and I'm not sure where to find that in the admin interface, but that would definitely be good to have for our chapter.
Also, being able to make "throwaway" email addresses for that purpose would be awesome.
Thanks in advance,
Will

**Comment by willgearty** [comment]
Oh, I may have found the email forwarding...is it the plain redirects in the Dbmail section?

**Comment by milescalabresi** [comment]
Yeah, the plain redirects is the place to do email forwarding. I don't know
how that interacts with various spam filters though.

**Comment by benjaminjkraft** [comment]
I'm not sure that it's possible* to make messages sent as a Gmail address look fully legitimate, because, quite simply, we're not Gmail.  So if you want the best shot at not being marked as spam, you'll need to send from a domain you control.**

I'm not sure plain redirects will work at the moment, because I'm not sure if we have MX records set up (see #1975).  But we can fix that, in which case the best bet is probably to send as e.g. splash@stanfordesp.org and then have diogenes forward that to your gmail.  In addition to that, though, there are a number of things we can do to make things better for both cases -- we should set SPF (and MX) records for all chapter sites, and make sure that even if we're setting gmail as the From address we set the Sender to be us.  If we wanted to go as far as possible, we could try sending through something like Mailgun or Sendgrid, who can do even more to get us trusted, but that costs money and may not be worth it.

*Well, we could send through Gmail SMTP servers, but we can only send 2000 messages/day, which wouldn't work for large chapters.  This would also require us storing the password to chapter gmail accounts, which I'd prefer not to do.
**In particular, you need to be able to set SPF and ideally also DKIM records for it.

**Comment by willgearty** [comment]
I played around with the plain redirects, and they seem to work fine (and aren't going to spam folders either), so everything seems to be working right now.
We just need to remember to use stanfordesp@stanfordesp.org from now on.
@benjaminjkraft , I don't really understand the MX stuff, but would that make the plain redirects completely dysfunctional (because they aren't right now)?

**Comment by benjaminjkraft** [comment]
@willgearty If it works now, it should keep working, unless I massively goof.

**Comment by willgearty** [comment]
Cool, thanks @benjaminjkraft and especially @milescalabresi for bringing this to my attention (a search of "spam" and "comm panel" in the issues brought up this one). Maybe I should trudge through more of these ancient github issues...

**Comment by benjaminjkraft** [comment]
On the original issue: I've set up MX and SPF records for diogenes (the former pointing to itself, and the latter mirroring learningu.org's, which points to diogenes, plato, and Google).  All of the subdomains are CNAMEs of diogenes, so they should all work correctly to both send and receive mail, and hopefully even not get marked as spam (as long as the emails are set from either an LU server or Google).  (That is, I didn't do exactly what aseering suggested, but I think what I did also works and it's easier to maintain.)

I'm not sure why emails are coming from *@diogenes.learningu.org by default -- that doesn't seem to match the code.  In any case, it's easy enough to just change the address and I think that's what people tend to do, so I'm going to call this resolved.  Feel free to open a new issue if you see more emails getting marked as spam or if the default sender address is wrong and causes any problems.

**Comment by benjaminjkraft** [comment]
Oh, one more thing: from a quick check, emails to username@whatever.learningu.org should also now work without creating a redirect, although plain redirects and class lists should take precedence.  If you see any problems, feel free to open a new issue.
