### ISSUE TITLE
Add a warning to ajax_clear_schedule before it works

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1410]
Accidental use of ajax_clear_schedule should be a lot less possible than it currently is.

**Comment by joeleg** [comment]
Simply issuing a get request on e.g. /manage/HSSP/2013_Summer/ajax_clear_schedule causes the schedule to clear. When modifying content, the request should use the post method

**Comment by benjaminjkraft** [comment]
It's intended to be used by a human (right?) so I think having the GET return an "are you sure?" page with the number of sections would be great, and then the button can just POST an empty form (with a CSRF token, ideally).

**Comment by luac** [comment]
Is it? I thought the "ajax_" in the name implied otherwise.

**Comment by mgersh** [comment]
Right before I created this issue, @gkanwar forwarded an email to me which claims that the way you do this is by hand. My best guess is that the "ajax_" in the name was probably a reference to the ajax scheduler (even though this has nothing to do with the ajax scheduler, but that's a different issue).

**Comment by joeleg** [comment]
Michael clarified that this is also used by a couple of clients including scripts and a Java client. It seems like a few things need to happen:

* There needs to be a preliminary step to prompt and capture the user confirmation. I suppose if we want to be extra careful, it could generate a unique token, in order to avoid accidentally clearing the schedule.

* The view that is responsible for clearing the schedule should not accept a GET request(this would still be inline with Ben's comment), and this could return a json list of sections.

* The client/scripts would need to be updated to handle the new workflow and response data

* It also sounds like this feature could potentially benefit from a simple form(as in Ben's previous comment)

**Comment by benjaminjkraft** [comment]
We should also not overengineer this thing -- I think it gets used probably
5 times a year across all sites (one for each program using the
autoscheduler, plus maybe a couple more in other scripts).  A simple
confirmation and a bit of CSRF protection should be more than enough.

**Comment by joeleg** [comment]
Ok, sounds good - I will simply implement a basic confirmation form and CSRF protection.
