### ISSUE TITLE
Make print schedules page say what it's doing.

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1538]
If you're using the print schedules page, it's not obvious what it's doing, so if another person walks up they may think they need to go back or something, or may otherwise disturb it.  Paul Kominers suggests the text "I AM THE THING THAT MAKES PRINTING WORK DON'T TOUCH ME".  (Due to the way the page works, this might be hard to fix.)

**Comment by luac** [comment]
Looking at the page, it seems that the difficulty is that the page relies on printing itself, and we don't want to print extra material?

I wonder if there is a way to make the printself callback hide the rest of the page so that it only prints the schedule image.

That would also be nice because we could potentially use that to add useful things to the page, like a log of recent print requests.

**Comment by benjaminjkraft** [comment]
Yeah, that's the difficulty, and your suggestion might be a good fix.
