### ISSUE TITLE
Print usernames and ID numbers on nametags

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1542]
Like we do on schedules.  This would make it easier to print new schedules for students who lose them but still have their nametag.

Potentially relevant files:
esp/esp/program/modules/handlers/programprintables.py

**Comment by jerrywu64** [comment]
Title should be "...on..."?

**Comment by benjaminjkraft** [comment]
Yup, fixed.

**Comment by betaveros** [comment]
Fixed in template override in actual database; I inserted this before the URL and phone number (which already exists in the template in the codebase):
```
        {% if user.id %}
          <span class="studentid">{{ user.username }} (ID: {{ user.id }})</span><br />
        {% endif %}
```

If you look at our the template override, you will also there is a second `<td>` with a second copy of a URL that is not visible and looks deletable, but the existence of the `<td>` keeps the rest of the layout working and I am not sure if I want to try to untangle that.
