### ISSUE TITLE
No "cancel edit" button for QSD

### ISSUE THREAD

**Issue by szhu** [learning-unlimited/ESP-Website#1555]
If I am editing a QSD, there is no easy way to cancel the edit. I may want to cancel it if:
- I want to revert my current, unsaved edits
- I realized I was being served the cached version and want to force-reload to edit the current version
- I do not want the page to refresh after I click out, for example, if I accidentally clicked it and have some other progress in the page, like a filled-out form

Related to that last point, sometimes I don't want text box to disappear after losing focus. I often copy/paste stuff from other windows or tabs and don't want to lose the cursor position or wait 5 seconds for the page to refresh, possibly with an older, cached version.

Most websites have explicit edit and save buttons. Is there a reason the situation is different here?

Btw, I know I can go to QSDs in the admin interface to revert changes, but that is not straightforward. (A link to the corresponding QSD admin page woud help.)

**Comment by luac** [comment]
On normal QSD pages, there is an "edit this page" link that takes you to a non-inline page for editing. 

Perhaps this should be made more obvious, or the inline editor should be improved in the ways you described so that it's no longer necessary to have two different interfaces.

**Comment by jerrywu64** [comment]
There was also a complaint about accidental clicks mentioned, though.
Perhaps if you click on the place where you open the inline editor, you can
cancel edits after prompt?

-Jerry Wu

**Comment by szhu** [comment]
Nope, that causes the page to refresh too.

I'd be open to working on AJAX save so that the page never has to refresh, given you guys think it's a good idea.

**Comment by jerrywu64** [comment]
Oops, I meant that it should be a feature that clicking there should do
that.

-Jerry Wu

**Comment by benjaminjkraft** [comment]
> Perhaps this should be made more obvious, or the inline editor should be improved in the ways you described so that it's no longer necessary to have two different interfaces. 

++.  I much prefer to use the full edit interface for anything nontrivial, but it's harder to get to.

**Comment by szhu** [comment]
What do you guys think about a having AJAX save? I think that's a lot better than having to load a new page with each save.

**Comment by benjaminjkraft** [comment]
I don't think it's particularly important, and there are some tricky bits to be careful with respect to caching, but if you're offering to implement it I'm certainly happy to have it :-) .

**Comment by jmoldow** [comment]
It sounds like there are at least three different issues being discussed here:
- Accidental activation of the inline QSD editor.
- Accidental saving of the QSD / no ability to cancel editing without saving / automatic rather than explicit saving.
- AJAX saving vs. POST and reload.

@szhu, can you edit this issue to be about one of the first two, and then create two new tickets for the other two?

On the subject of accidental activation:

I don't like the inline QSD because it prevents me, as an admin, from using the site normally. I want to be able to select/copy text, click links, and mindlessly click around the page, without worrying about activating the inline QSD. I think that the block of text should act as a normal block of text, the same as for non-admin users, until some explicit action is done to activate the editor. Probably via some sort of button click. Or by clicking the currently existing "Click here to edit the text" message at the top of QSD blocks. But I don't think that you should be able to click anywhere in the text to open the editor.

**Comment by benjaminjkraft** [comment]
> Or by clicking the currently existing "Click here to edit the text" message at the top of QSD blocks.
This is what I currently see (Firefox on Ubuntu); is that not the behavior for you?

**Comment by jmoldow** [comment]
Hmm, you're right. Did we change the behavior recently? Or am I just crazy? I thought the behavior was as I described... Anyway, glad to see the behavior is already what I wanted it to be :P

I'll edit my comment.

**Comment by betaveros** [comment]
Closed by #2247
