### ISSUE TITLE
Derived field ClassSection.enrolled_students is often incorrect

### ISSUE THREAD

**Issue by luanths** [learning-unlimited/ESP-Website#1661]
See https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/models/class_.py#L1005

DerivedField is supposed to update the field whenever the cached function is invalidated, so `sec.enrolled_students` should match `sec.num_students()` in all cases. However, empirically it's not so reliable. I just checked against MIT ESP's database, and 1120 out of 10980 `ClassSection`s have a mismatch. Interestingly, most of these have `enrolled_students` greater than `num_students()` (953), and all but a few of these are from recent-ish programs (ID greater than 5600).

This could arise due to #1463, or signals not being connected properly somewhere.

**Comment by benjaminjkraft** [comment]
Random thought: if the cache expires due to memcache evicting it (or a manual cache flush not using the page) rather than argcache expiring it, will the DerivedField get updated?  I wouldn't expect this to happen a lot, but it might happen occasionally; I know I sometimes flush the cache manually if the server is slow enough that loading the page would take a while.

**Comment by luac** [comment]
No, it won't.

**Comment by willgearty** [comment]
As far as I can tell, this appears to be fixed. I don't see any mismatches in my dev server, and the `enrolled_students` field appears to update properly when a student is enrolled/unenrolled (although only if you re-get the `ClassSection` object).
