### ISSUE TITLE
Scheduling checks: a way to hide false positives

### ISSUE THREAD

**Issue by luac** [learning-unlimited/ESP-Website#1687]
This could be an alternative resolution for issues such as those discussed in #1596, #1597.

**Comment by mgersh** [comment]
Implementation idea: each item has something you can click on to hide it, which happens entirely client-side. It doesn't persist across refreshes, but it probably reduces the need for refreshing, since you can click to hide something once you're done handling it instead of refreshing to clear out clutter.

**Comment by benjaminjkraft** [comment]
I like this idea.  It might not actually be that hard to persist it across reloading a single check without refreshing the page.  In theory we could persist beyond that using cookies, but that might be more work.  One disadvantage is that you can't share with someone else, so that the same person has to be keeping track of the same check.  But that's usually what happens anyway.

**Comment by benjaminjkraft** [comment]
Another thing: we should make sure to have an unhide button.  Or, it might be easier to just put the hidden ones in very light gray, so that they are still readable, but not as obvious.  Or it might be better to just not try to keep beyond reloads for this reason.
