### ISSUE TITLE
manage///surveys/top_classes stopped working at some point

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1826]
It doesn't show any classes.

**Comment by willgearty** [comment]
I think this is because we are looking for ratings for classes:
https://github.com/learning-unlimited/ESP-Website/blob/1628bc2422b5954ac3555c7e007e277fcd74afa6/esp/esp/survey/views.py#L428
but the survey answers are associated with class sections:
https://github.com/learning-unlimited/ESP-Website/blob/1628bc2422b5954ac3555c7e007e277fcd74afa6/esp/esp/survey/models.py#L149-L169
