### ISSUE TITLE
Link to program survey results from list of all modules

### ISSUE THREAD

**Issue by jerrywu64** [learning-unlimited/ESP-Website#2008]
there should exist a link to /manage/Sploosh/3010/surveys/review (or if not this page, then some other relevant page) from the complete module list on /manage/.../main.

**Comment by mgersh** [comment]
It's possible that I caused this (and a similar bug on the learn/teach side) when I added the survey/surveys aliases in #1688. I don't have time to check right now, but if you're working on this, look there. (The page it should be linking to is just /surveys, since that's the main_call, not /surveys/review.)

**Comment by willgearty** [comment]
Don't you just need to make `isStep()` return `True` for the survey management module?
