### ISSUE TITLE
Class durations are not shown in manageclass or classsearch

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#2025]

**Comment by kkbrum** [comment]
I've /almost/ done this, but can't fix the following problem, mainly because I just don't really get what's happening with how durations are stored:

![image](https://user-images.githubusercontent.com/25392075/37744319-b698ae92-2d44-11e8-8cfc-7fffae654c89.png)

The code for how far I got is in the branch manage-class-duration if anyone wants to continue my effort :/

From what I can tell, classsearch does show duration (beside the section number):
![image](https://user-images.githubusercontent.com/25392075/37744401-4facf43a-2d45-11e8-9b78-376ee6cf8c7a.png)

**Comment by willgearty** [comment]
Is the goal here to show the duration or allow for it to be edited?

**Comment by kkbrum** [comment]
Well, I can very easily display it at the top of manage with the other not editable stuff, but im assuming they wanted it to be editable? not sure

**Comment by willgearty** [comment]
Well, I found one problem, but it's apparently not the main problem. I'm stumped.

![image](https://user-images.githubusercontent.com/7232514/37749846-2044309e-2d47-11e8-8e3b-41b0644304a9.png)

**Comment by kkbrum** [comment]
But maybe from your contribution I can look again and suddenly succeed! I shall retry tomorrow- at least I have some new material to work with :)

**Comment by willgearty** [comment]
Huzzah!

![image](https://user-images.githubusercontent.com/7232514/37750671-824c518c-2d4b-11e8-8671-8356087503f9.png)

Fun fact, your way works if you have any durations aside from full hours. The problem was that somewhere along the line, the decimal places (e.g. 1.00) were getting cut off (e.g. 1), and so you need to convert to a float and then back to a Decimal to match what the form wants.

**Comment by kkbrum** [comment]
oh dear. well thank you! You can have a gold star now 
![image](https://user-images.githubusercontent.com/25392075/37750828-4f3b7d58-2d65-11e8-994a-962c866d3f43.png)

**Comment by willgearty** [comment]
For the record, the problem is [here](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/models/__init__.py#L936). The original durations start as seconds, so whole hours end up as whole numbers.
