### ISSUE TITLE
Document tags

### ISSUE THREAD

**Issue by btidor** [learning-unlimited/ESP-Website#2038]
We should have a page in `docs/dev/` that explains how to add and remove tags. In particular, an explanation of how the list of all tags works would be great.

**Comment by mgersh** [comment]
What would you like explained that isn't in the comments in `tagdict/__init__.py`? Or is finding that file the problem? We could make the warnings more clear about where the lists live.

**Comment by btidor** [comment]
For me, the real problem is that if I wasn't around when this was added, I'd have no idea to look in `tagdict/__init__.py`. If someone wanted to write a little about what tags are and how they work, that would be nice, but secondary.

**Comment by benjaminjkraft** [comment]
It may even be worth having a `docs/admin/` page for this, perhaps with a warning "messing with tags is dangerous and please don't break things", because there are a lot of times we tell admins to edit tags, either by email or in other docs.  There might be a wiki page that already has some text on this, I'm not sure.

**Comment by benjaminjkraft** [comment]
Now that diogenes is up, I can be more specific: in particular it might be useful to migrate some or all of http://wiki.learningu.org/Customize_behavior_with_Tags into the repo.

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/2916
