### ISSUE TITLE
Can't write multiple words on Fruitsalad tabs

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2461]
E.G. "Old Courses" will just display as "Old" on the tab

**Comment by bhorowitz** [comment]
Hmm, it seems look okay here? https://nusplash.learningu.org/

**Comment by milescalabresi** [comment]
That's weird... on BC's site, when you set 
![image](https://user-images.githubusercontent.com/5506191/32523849-21ebb6d0-c3eb-11e7-9272-1c57e43f6f40.png)

then it displays
![image](https://user-images.githubusercontent.com/5506191/32523868-39af99da-c3eb-11e7-91cb-1cdc0836acef.png)

**Comment by betaveros** [comment]
I think your two words are just too wide, with the result that it wraps to a new line, but since the tab has a fixed height, the second line just falls off the tab and gets hidden behind the last tab. Here's an example with manually edited DOM and selected text:
<img width="153" alt="screen shot 2017-11-08 at 9 24 47 pm" src="https://user-images.githubusercontent.com/3482833/32585434-772071e6-c4cb-11e7-94ad-30adf41560f2.png">

**Comment by benjaminjkraft** [comment]
Perhaps we should have a warning over ~8 characters that this may be too big for the tabs?  Or just do `white-space: nowrap` or whatever in the tabs, that way at least it will overflow in an obvious way if it's too big

**Comment by milescalabresi** [comment]
Ah! Thanks. I like Ben's ```white-space: nowrap``` idea.
