### ISSUE TITLE
Teacher class registration skipping class IDs

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2631]
I'm not really sure what's going on here, but for some reason, we're seeing weird gaps in the numbering of classes. We haven't deleted any classes yet, and I went back to our last program and don't see anything like this. The numbers seem to be incrementing fine now.

For example, we have the following gaps:

- C6582 to M6615
- L6671 to L6704
- plus a bunch of smaller gaps of 2-4

**Comment by benjaminjkraft** [comment]
Class numbers are not guaranteed to be sequential; they are assigned by the database and it doesn't make any such guarantee for IDs.  (For example, if some request starts to create a class, then crashes, it may allocate an ID, but not use it; it will not be reused since IDs *are* generally ordered.  They are also global so if you have classes created in test programs those can "steal" the ID.)

If you need sequential IDs for some reason, you'll need to describe the use case more, although the answer may honestly be "it's just too hard".
