### ISSUE TITLE
Popularity printable takes a long time with big programs

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2726]
The new printable from #2712 works just fine with small programs, but with large programs it takes a really long time to load (the Stanford program I tested it on never even finished loading). It appears the vast majority of the time comes from actually evaluating the QuerySet that I built here: https://github.com/learning-unlimited/ESP-Website/blob/a04ff41cd1c572160c87ad3f204b9d5ae3b1be68/esp/esp/program/modules/handlers/programprintables.py#L317-L324

**Comment by willgearty** [comment]
Ah, I played around with the code on the server and it only takes a long time to evaluate the QuerySet if you do line 323:
https://github.com/learning-unlimited/ESP-Website/blob/a04ff41cd1c572160c87ad3f204b9d5ae3b1be68/esp/esp/program/modules/handlers/programprintables.py#L323

**Comment by benjaminjkraft** [comment]
The thing you want to do to understand this is to figure out the actual SQL it's executing.  I know of two ways to do so:
1. run the code in a shell, then after line 324 run `print classes.query` (I think -- something like that)
2. use the django debug toolbar and find the slow query in the queries tab

Once you do, you see if you can find the problem, or post the query here.  My guess is that the problem here is we're joining to two very large tables (`StudentRegistration and StudentSubjectInterest` have millions of rows) which means we need to make sure that everything they do is done efficiently.  (We aren't very good about setting up proper indices to make queries fast.)  If you want, you can try running `EXPLAIN ANALYZE <query>;` in a `psql` shell (`sudo -u postgres psql -d stanforddjango`) and it will give you a ton of output about exactly how it executed the query which may allow you to figure out what's slow, although not necessarily how to make it faster.  One possibility for making it faster is to do the two annotation queries separately, and join them on the client -- since we're fetching all the data anyway it's not much slower, and it will avoid any chance of postgres trying to do an overly complicated join.  But hopefully we can find a cleaner way to get it to do what we want.

**Comment by willgearty** [comment]
Thanks for the info, @benjaminjkraft!

Here's the query for lines 317-322:

SELECT "program_class"."id", "program_class"."title", "program_class"."parent_program_id", "program_class"."category_id", "program_class"."class_info", "program_class"."allow_lateness", "program_class"."message_for_directors", "program_class"."class_size_optimal", "program_class"."optimal_class_size_range_id", "program_class"."grade_min", "program_class"."grade_max", "program_class"."class_size_min", "program_class"."class_style", "program_class"."hardness_rating", "program_class"."class_size_max", "program_class"."schedule", "program_class"."prereqs", "program_class"."requested_special_resources", "program_class"."directors_notes", "program_class"."requested_room", "program_class"."session_count", "program_class"."purchase_requests", "program_class"."custom_form_data", "program_class"."status", "program_class"."duration", "program_class"."timestamp", COUNT(CASE WHEN "program_registrationtype"."name" = Priority/1 THEN 1 ELSE NULL END) AS "priority1", COUNT(CASE WHEN "program_registrationtype"."name" = Priority/2 THEN 1 ELSE NULL END) AS "priority2", COUNT(CASE WHEN "program_registrationtype"."name" = Priority/3 THEN 1 ELSE NULL END) AS "priority3" FROM "program_class" LEFT OUTER JOIN "program_classsection" ON ( "program_class"."id" = "program_classsection"."parent_class_id" ) LEFT OUTER JOIN "program_studentregistration" ON ( "program_classsection"."id" = "program_studentregistration"."section_id" ) LEFT OUTER JOIN "program_registrationtype" ON ( "program_studentregistration"."relationship_id" = "program_registrationtype"."id" ) WHERE "program_class"."parent_program_id" = 31 GROUP BY "program_class"."id", "program_class"."title", "program_class"."parent_program_id", "program_class"."category_id", "program_class"."class_info", "program_class"."allow_lateness", "program_class"."message_for_directors", "program_class"."class_size_optimal", "program_class"."optimal_class_size_range_id", "program_class"."grade_min", "program_class"."grade_max", "program_class"."class_size_min", "program_class"."class_style", "program_class"."hardness_rating", "program_class"."class_size_max", "program_class"."schedule", "program_class"."prereqs", "program_class"."requested_special_resources", "program_class"."directors_notes", "program_class"."requested_room", "program_class"."session_count", "program_class"."purchase_requests", "program_class"."custom_form_data", "program_class"."status", "program_class"."duration", "program_class"."timestamp"

Then, if you add line 323, the query becomes this:
SELECT "program_class"."id", "program_class"."title", "program_class"."parent_program_id", "program_class"."category_id", "program_class"."class_info", "program_class"."allow_lateness", "program_class"."message_for_directors", "program_class"."class_size_optimal", "program_class"."optimal_class_size_range_id", "program_class"."grade_min", "program_class"."grade_max", "program_class"."class_size_min", "program_class"."class_style", "program_class"."hardness_rating", "program_class"."class_size_max", "program_class"."schedule", "program_class"."prereqs", "program_class"."requested_special_resources", "program_class"."directors_notes", "program_class"."requested_room", "program_class"."session_count", "program_class"."purchase_requests", "program_class"."custom_form_data", "program_class"."status", "program_class"."duration", "program_class"."timestamp", COUNT(CASE WHEN "program_registrationtype"."name" = Priority/1 THEN 1 ELSE NULL END) AS "priority1", COUNT(CASE WHEN "program_registrationtype"."name" = Priority/2 THEN 1 ELSE NULL END) AS "priority2", COUNT(CASE WHEN "program_registrationtype"."name" = Priority/3 THEN 1 ELSE NULL END) AS "priority3", COUNT(DISTINCT "program_studentsubjectinterest"."id") AS "ssi" FROM "program_class" LEFT OUTER JOIN "program_classsection" ON ( "program_class"."id" = "program_classsection"."parent_class_id" ) LEFT OUTER JOIN "program_studentregistration" ON ( "program_classsection"."id" = "program_studentregistration"."section_id" ) LEFT OUTER JOIN "program_registrationtype" ON ( "program_studentregistration"."relationship_id" = "program_registrationtype"."id" ) LEFT OUTER JOIN "program_studentsubjectinterest" ON ( "program_class"."id" = "program_studentsubjectinterest"."subject_id" ) WHERE "program_class"."parent_program_id" = 31 GROUP BY "program_class"."id", "program_class"."title", "program_class"."parent_program_id", "program_class"."category_id", "program_class"."class_info", "program_class"."allow_lateness", "program_class"."message_for_directors", "program_class"."class_size_optimal", "program_class"."optimal_class_size_range_id", "program_class"."grade_min", "program_class"."grade_max", "program_class"."class_size_min", "program_class"."class_style", "program_class"."hardness_rating", "program_class"."class_size_max", "program_class"."schedule", "program_class"."prereqs", "program_class"."requested_special_resources", "program_class"."directors_notes", "program_class"."requested_room", "program_class"."session_count", "program_class"."purchase_requests", "program_class"."custom_form_data", "program_class"."status", "program_class"."duration", "program_class"."timestamp"

And if you do only lines 317 and 323:
SELECT "program_class"."id", "program_class"."title", "program_class"."parent_program_id", "program_class"."category_id", "program_class"."class_info", "program_class"."allow_lateness", "program_class"."message_for_directors", "program_class"."class_size_optimal", "program_class"."optimal_class_size_range_id", "program_class"."grade_min", "program_class"."grade_max", "program_class"."class_size_min", "program_class"."class_style", "program_class"."hardness_rating", "program_class"."class_size_max", "program_class"."schedule", "program_class"."prereqs", "program_class"."requested_special_resources", "program_class"."directors_notes", "program_class"."requested_room", "program_class"."session_count", "program_class"."purchase_requests", "program_class"."custom_form_data", "program_class"."status", "program_class"."duration", "program_class"."timestamp", COUNT(DISTINCT "program_studentsubjectinterest"."id") AS "ssi" FROM "program_class" LEFT OUTER JOIN "program_studentsubjectinterest" ON ( "program_class"."id" = "program_studentsubjectinterest"."subject_id" ) WHERE "program_class"."parent_program_id" = 31 GROUP BY "program_class"."id", "program_class"."title", "program_class"."parent_program_id", "program_class"."category_id", "program_class"."class_info", "program_class"."allow_lateness", "program_class"."message_for_directors", "program_class"."class_size_optimal", "program_class"."optimal_class_size_range_id", "program_class"."grade_min", "program_class"."grade_max", "program_class"."class_size_min", "program_class"."class_style", "program_class"."hardness_rating", "program_class"."class_size_max", "program_class"."schedule", "program_class"."prereqs", "program_class"."requested_special_resources", "program_class"."directors_notes", "program_class"."requested_room", "program_class"."session_count", "program_class"."purchase_requests", "program_class"."custom_form_data", "program_class"."status", "program_class"."duration", "program_class"."timestamp"

I'm not really sure what to look for here in terms of what's slowing this down. There's obviously a lot of fields here, most of which we don't need for the downstream stuff, but would that be slowing us down?

Another thought I had was to do these DB calls for each class independently. We could either make methods for ClassSubject to count these things or just do a loop over a list of classes. In the former case, we can just call those methods client-side in the template (although it might be messy because we need to specify the priority level somehow)? In the latter case, we would just add fields to the class objects as we loop through them. I quickly tested running lines 317-323 but with a filter for a specific class, and it runs much faster. Even scaled to the size of the entire program, I think it'll be faster than what I'm doing right now?

Anyways, let me know what you think @benjaminjkraft or if you see any obvious solutions based on the queries I included above.

**Comment by willgearty** [comment]
Also, I was pretty sure I fixed this, but I think the priority numbers are still getting multiplied by the SSI values. I might need to include a `distinct()` call.

**Comment by benjaminjkraft** [comment]
Yeah, so this is what I was worried about.  (Note, in the below, SR = StudentRegistration (i.e. priority) and SSI = StudentSubjectInterest (i.e. star).)

If you look at the second query it's super verbose because of all the fields but the important part is the joins which (with a little formatting stripped) are not too complicated:
```
SELECT [fields]
FROM
  program_class
  LEFT OUTER JOIN program_classsection ON program_class.id = program_classsection.parent_class_id
  LEFT OUTER JOIN program_studentregistration ON program_classsection.id = program_studentregistration.section_id
  LEFT OUTER JOIN program_registrationtype ON program_studentregistration.relationship_id = program_registrationtype.id
  LEFT OUTER JOIN program_studentsubjectinterest ON program_class.id = program_studentsubjectinterest.subject_id
WHERE [conditions]
```
Now, we have to remember how a JOIN works (the fact that it's LEFT OUTER actually won't be relevant here).  You've got some field you're matching on and you find all the rows on the left side and all the rows on the right side and you match them up and output a row for each such pair.  Note, though, that if you have multiple rows on the right that match the same row on the left, you have multiple rows in the output.  So just looking at the first two tables,
```
  program_class
  LEFT OUTER JOIN program_classsection ON program_class.id = program_classsection.parent_class_id
```
is going to have a row for each class for each child section.  This is fine -- that's still only one row per section.  If we add the next join:
```
  LEFT OUTER JOIN program_studentregistration ON program_classsection.id = program_studentregistration.section_id
```
we have a row for each class for each child section for each SR corresponding to that section.  That's still fine -- we will still only have one row per SR, and so at worst we're traversing like a million rows which is not instant, but doable.  The next join is not very interesting -- it just matches up the corresponding RegistrationTypes, which doesn't do much.  But the last one -- which is the one that gets added in the second query -- is the problem.  Now we do:
```
  LEFT OUTER JOIN program_studentsubjectinterest ON program_class.id = program_studentsubjectinterest.subject_id
```
and we have a row for each class for each child section for each SR corresponding to that section for each SSI corresponding to that section.

And now we have a problem!  For a single class X1234 with a single section X1234s1, 100 SRs, and 200 SSIs, before we would output 100 rows: one for each SR.  Now, instead, we output 20000 rows: one for each SR (100) for each SSI (200).  That is, we basically end up doing a CROSS JOIN of the SRs and SSIs for each class.  Add that up over all of Stanford Splash, and I bet you get more like 100M or 1B rows, which is too many to handle.  (And, amusingly, you get the wrong answer: for "priority1" you end up with the number of Priority/1s times the number of SSIs, for "ssis" you get the number of SSIs times the number of SRs, and so on -- if you think carefully about what the rows in the full join are, and what we're counting, you can see this.)

It's not obvious to me whether this is the intended semantics of the django ORM, or a bug -- it seems surprising to me but it's possible it's documented -- but in any case the query it's generating is not the query we want.  This [SO answer](https://stackoverflow.com/questions/6795202/django-count-in-multiple-annotations) describes it a bit more -- it's possible their approach of using `Count(..., distinct=True)` will work (you'd need it on both counts), but it's possible the postgres query optimizer won't be quite smart enough to do that the efficient way -- you're basically saying "generate all those rows, then count the ones where this field is distinct" and it has to know that it can figure out the distinct ones without generating all the rows.  (`.distinct()` on the whole query definitely will not work -- each row corresponds to a unique (SR, SSI) pair and they are thus already distinct.  Also, doing each class independently won't help.  You still have to traverse all the same rows, you just do it one class at a time.)

But what will help is doing the SR and SSI queries separately: by doing that you avoid joining SR and SSI at the same time, and thereby the combinatorial explosion and its performance and confusing results.  You'll have to join up the classes in python, but such is life.  It'll look something like:
```
classes = ClassSubject.objects.filter(parent_program = prog)

# Fetch SR classes
sr_classes = classes
for priority in priorities: 
    sr_classes = sr_classes.annotate(**{'priority' + str(priority): Count( 
    Case(When(sections__studentregistration__relationship__name='Priority/' + str(priority), then=1), default=None, output_field=IntegerField() 
    ))}) 

# Fetch SSI classes
ssi_classes = ssi_classes.annotate(ssi=Count('studentsubjectinterest', distinct=True))

# Merge the two (by ID)
by_id = {}
for subject in sr_classes:
    by_id[subject.id] = subject
for subject in ssi_classes:
    if subject.id in by_id:
        by_id[subject.id].ssi = subject.ssi
    else:
        by_id[subject.id] = subject

# Sort
classes = sorted(subject.values(), key=lambda s: s.ssi)
```
(except the details will be different depending exactly what you want to do and whether you're using `.values()` or `.values_list()` or neither and so on).

(It's possible there is a way to write things to get the ORM to do this -- it's surely possible in SQL by doing something like
```
SELECT ...
FROM (
  SELECT ..., COUNT(studentregistration)
  FROM class JOIN section JOIN studentregistration
  WHERE ...
) JOIN (
  SELECT ..., COUNT(studentsubjectinterest)
  FROM class JOIN section JOIN studentsubjectinterest
  WHERE ...
) WHERE ...
```
but thinking about how to write that through Django makes my brain hurt.  It's just not the sort of things that ORMs express cleanly.)

**Comment by willgearty** [comment]
Thank you so much @benjaminjkraft! I'll look into implementing that this weekend!
