### ISSUE TITLE
Userview availability link shows without availability module

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2770]
Userview "check availability" link shows even if the availability module isn't enabled for that program.

**Comment by willgearty** [comment]
Ah, we want to check for the "Teacher Availability Checker" module, not "Teacher Availability" module.

**Comment by kkbrum** [comment]
So this, as far as I can tell, is not that easy--

The teacher availability checker and the teacher availability appear have the same handler called [AvailabilityModule](https://github.com/learning-unlimited/ESP-Website/blob/875106d2789fdbe5cdddac751a5ac9681ae7fe4f/esp/esp/program/modules/handlers/availabilitymodule.py#L55) so then the [hasModule ](https://github.com/learning-unlimited/ESP-Website/blob/4dd466d23b6286902fc71b333a355c8420d619d1/esp/esp/program/models/__init__.py#L1035) function takes in the handler name and is just checking whether either of the component modules have been enabled. So I think the hasModule function would need to get updated to actually take in one of the component module names instead of the handler name? but tbh kinda over my head of what the heck a handler vs module is so I'm going to toss it back to you @willgearty 🙃

**Comment by willgearty** [comment]
Yep, you are absolutely correct. `hasModule` is filtering by handler name, which is the same for both of the modules. We could theoretically change `hasModule` to filter by `Admin Title` or add an extra option to specify a `module_type` to filter by. But ultimately we probably want to fix the problem at the source and split this handler into two handlers, as @benjaminjkraft has been doing with other "double-module" cases like this one in #2125.
