### ISSUE TITLE
Userview program selection dropdown does not actually select the default in all cases

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2787]
![image](https://user-images.githubusercontent.com/25392075/62093622-eff8e880-b247-11e9-8ca8-ec8c4f3573af.png)

Although a program appears in the dropdown automatically as if it has been selected, there is no program actually selected until you go and click on one. Either make there be a blank option on the dropdown and have that be the initialization or have it actually select the program it initializes to.

This is for a teacher who has not filled out a teacher info. I think if there is teacher profile info it autoselects the most recent program with profile info or something of the sort.

**Comment by willgearty** [comment]
Looks like the default program is set here:
https://github.com/learning-unlimited/ESP-Website/blob/82d1e03c6322166f724b732893d94b54106584ae/esp/esp/program/views.py#L367

So if a user doesn't have any program profiles, then the program is None or something, so none of the dropdown options are selected (but since there isn't a null option in the dropdown, it looks like the first option is selected).

So in that case, it looks like the easiest thing to do is just add a null option to the select here:
https://github.com/learning-unlimited/ESP-Website/blob/82d1e03c6322166f724b732893d94b54106584ae/esp/templates/users/userview.html#L27-L33
