### ISSUE TITLE
Checking for teacher profile before showing schedule on userview page broken

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2797]
Unfortunately checking for teacher_info as a way for only showing the teacher schedule on the userview if relevant is not working because it is pulling the last profile, not the profile for the program.

**Comment by willgearty** [comment]
Yeah, I think the real solution here is to get the specific profile for the program if there's one selected (or if there's one chosen as the default) instead of just the most recent profile. It would be a !was to do that in the template, so we should really do that in the handler and send the profile as part of the context.
