### ISSUE TITLE
Palette adding and removing colors has wierd behavior. (Themes)

### ISSUE THREAD

**Issue by nrjean** [learning-unlimited/ESP-Website#2907]
There is some really weird behavior with the palette in themes. It's hard to describe exactly what is going on, however here are some behaviors I was able to replicate.

1. Some base colors are impossible to remove
2. Removing more than one color at a time is impossible.

Compound this with the fact that you can only remove the "last color" and this means it is impossible to delete some colors from the website. (Which is a big pain if two colors are very similar to one another)

**Comment by willgearty** [comment]
Can you give a set of instructions to replicate what you're trying to do? What is the expected outcome, and what is the actual outcome?

**Comment by nrjean** [comment]
Mechanics:

1. Go to palette (in customize the themes)
2. Click remove last color more than once - or - click add another color more than once
3. Click update palette
This will result in no change to the palette

For the second issue of some colors being unremovable from the palette I don't really have a good way of replicating it, however - if you click remove last color enough times, you'll encounter a color that just won't go away

**Comment by willgearty** [comment]
I think I've figured out what's going on here. It's a combination of the following:

1. We always include any LESS variable colors from the theme in the palette:
https://github.com/learning-unlimited/ESP-Website/blob/e5cd5acfc62fa22cc4f69d78a81b16c785134c86/esp/esp/themes/controllers.py#L568-L574

2. We sort the palette before it is displayed:
https://github.com/learning-unlimited/ESP-Website/blob/e5cd5acfc62fa22cc4f69d78a81b16c785134c86/esp/esp/themes/controllers.py#L577

3. As @nrjean stated above, you can only ever remove the last color.
4. If you remove ALL of the colors in the palette, it doesn't update the palette:
https://github.com/learning-unlimited/ESP-Website/blob/e5cd5acfc62fa22cc4f69d78a81b16c785134c86/esp/esp/themes/views.py#L217-L218

Therefore, in order to remove a custom color, you will need to remove a lot of colors from the palette (most of which will return because they are LESS variables for the theme).

I'm thinking of two separate changes to fix this:

1. For the palette editing section, separate the LESS variable palette from the custom palette. Alternatively, always put the custom colors AFTER the LESS variable colors (and maybe don't remove duplicates?)
2. Allow for removing any color from the palette, not just the last one.
