### ISSUE TITLE
QSD buttons don't show correctly in big picture

### ISSUE THREAD

**Issue by shugeluo** [learning-unlimited/ESP-Website#2926]
![image](https://user-images.githubusercontent.com/18090629/75224440-58b42f00-575d-11ea-88be-3152739dd4c0.png)

Buttons on the Berkeley Splash editing interface don't show colors so the text are hard to read.

![image](https://user-images.githubusercontent.com/18090629/75224449-5ce04c80-575d-11ea-8562-9b0fd1a1b10a.png)

**Comment by nrjean** [comment]
![image](https://user-images.githubusercontent.com/60372830/75283461-f1d85980-57e0-11ea-8ca5-dcba06a93728.png)

Note - this is due to btn having color #f8f8f8 and overriding the styling intended for each of these buttons. Simple disabling background: f8f8f8 fixes this issue but may (will) introduce issues with other buttons. Perhaps adding an !important tag could be the simplest way to fix this
