### ISSUE TITLE
Surveys link should condition on modules

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3063]
The "View and Manage Surveys" link on the admin portal should condition on some modules. Right now i think it is always listed, but if the relevant modules aren't enabled, it leads to an error 404 page, ie https://dev3.learningu.org/manage/Splash/2012_Fall/surveys

**Comment by willgearty** [comment]
I think @milescalabresi made this decision because the survey modules are always included by default from now on.

**Comment by milescalabresi** [comment]
Yes, but I made that decision as a temporary fix. I think the long-term fix will involve a more comprehensive reworking of the admin portal. So adding the condition that @kkbrum suggests is a good one (if for whatever reason someone really wanted to turn off the surveys) because that will ultimately get included in the rework. Imo it's not necessarily a crucial fix for SR12 for that reason, but I don't mind making it if you think it is.
