### ISSUE TITLE
User Pronouns

### ISSUE THREAD

**Issue by nrjean** [learning-unlimited/ESP-Website#3182]
At this point we should really have a box in the sign up form somewhere for students and teachers to input their pronouns. Then these pronouns can be added to things like attendance sheets so that teachers and admins can access it. Sorta motivated by Rainstorm how many kids had pronouns in their zoom accounts. Being able to access this info when sending emails, talking to teachers etc plus letting teachers access this info is really important. Note this should probably be a field and not a dropdown menu due to the amount of options. I'm sure some fancy regex can be done to be verify the field so doesn't get abused.

**Comment by willgearty** [comment]
Yeah, right now we have a gender field that I believe needs to be turned on (off by default), but a short answer text field is probably a better way to do it now. We probably wouldn't want this to be something that is required (and probably off by default like the existing gender field), since some people might not want to list their preferred pronouns (and there's also the potential that the parent could see something in their profile). Since ultimately we want to empower students to choose who they provide this information to, I think a really important component of the implementation would be to make it clear who will be able to see this, such as potentially **teacher, admins, and anyone that has access to their account**.

If something is implemented, I imagine there are a bunch of places that such information _could_ be included. For example, teacher attendance pages and students nametags.
