### ISSUE TITLE
"Teachers of a student" filter is broken for multiple printables that use the USC

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3248]
Several of the printables use the USC, but they weren't updated for #3153, which adds a new form to the context for searching for a student to get the teachers of that student. I previously had to fix this for the nametags page: https://github.com/learning-unlimited/ESP-Website/commit/0a75bc31b584742224433ee87b6378f647766753. Is there a way for us to ensure it always gets included for pages that are using the USC?

**Comment by kkbrum** [comment]
I made some partial fixes on the moderators branch. I added the student search form to the context generated by "prepare_context" that was already being called for all the USC instances. This means people won't have to manually import the studentSearchForm and add it to the context. However, people will need to use ListGenModule.processPost and not process the post dictionary manually, but that was pretty much already the case. 

However, there are a couple of problems:

- [ ] in commit e051835, I added a TODO, because for some reason i wasnt able to import the ListGenModule into the usersearch.py and had to copy the process post function (not ideal). No idea why I can't import it
- [ ] The form for the teachers of a student filter only works for base lists, not for combination lists. I'm not sure why yet.

**Comment by willgearty** [comment]
For the form not working in the combo lists, it looks like it is because the javascript associated with the field uses the ID of the field, which should be unique, so it only works on the first instance of the form on the page:
https://github.com/learning-unlimited/ESP-Website/blob/98501776a014a01eeba8c8105ee2aca2a7d7bee3/esp/esp/db/forms.py#L61-L97
