### ISSUE TITLE
Update or remove estimate of time to send emails

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3503]
Our current email estimate 1.5 seconds * number of emails is very inaccurate. We should update it (ideally with some kind of ping to Sendgrid's API) or just remove it entirely.

**Comment by hwatheod** [comment]
The original reason for this 1.5 second per email estimate is because we were sending the emails directly and were afraid of being labeled as spam by the receiving end if we sent them too fast. So we artificially introduced a 1.5 second delay. But with SendGrid, they ought to be taking care of any necessary throttling for us since their whole purpose is to send large numbers of emails. We don't know (or care that much, in my opinion) what that rate is. So I think we should just get rid of the time estimate.

**Comment by willgearty** [comment]
MY understanding is that SendGrid sends our email almost immediately after we submit them via the API. I'm not sure there's a good way to estimate how long the whole process will take, though, so I agree with @hwatheod that maybe just getting rid of the estimate is a good idea (and instead, linking to the email status page, where they can monitor the status of the email).

**Comment by laraao** [comment]
Current text is:
`The email is in the process of being sent. To avoid being marked as a spam source, it will take approximately 1.5 seconds to email everyone on the list, so please be patient!`

Instead of listing an approximate time, users will instead be directed to monitor emails page at `/manage/emails`.
