### ISSUE TITLE
Account-activation-email history

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#43]
We should log account-activation e-mails, and allow (and have a UI for) re-sending them

**Comment by benjaminjkraft** [comment]
The emails get cc'ed to the server email, which can be set up to go somewhere.  (For MIT ESP it goes to an archive gmail.)  If there's a particular other place people would like logs to go, please reopen.  (We could log them to the server's logs, but that doesn't seem that useful since it's usually admins who might want to look into them.
