### ISSUE TITLE
Comm Panel -- new filters

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#46]
- Number of class hours
- Whether student requested text messages
- Individual teaching and interviewing slots

(If you know how to add filters in general and you know how to query for something by hand, it's very easy to add a specific filter.  But you have to learn those two things first, which takes some effort.  So the "Easy" tag is conditional.)

**Comment by kkbrum** [comment]
I'm going to assume that since there is a group text panel (invented after this issue), there is no need for the comm panel filter by whether a student has elected text messages since this is built into the group text panel. There is also the option to see whether a student elected text messages as a field on the AUL. I think these two things should cover whatever use cases were desired in 2011.
