### ISSUE TITLE
Simplify program creation form

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#608]
We've had many requests, most recently from Chicago, to simplify the program creation form, especially when it comes to selecting program modules.  The defaults should be "correct" and any error messages should be clear.

**Comment by milescalabresi** [comment]
I'm not sure if this is the right place to post this (versus #220 or a new issue entirely), but now the "program modules" selection seems to be the most difficult part of the program creation form. More generally, lumping all these modules together as the same kind of object for admins doesn't make sense to me. There are not enough (any?) useful error messages (even to the server log). The [new documentation](https://github.com/learning-unlimited/ESP-Website/blob/e601c821223fb86189653aa766d9b6c85ba8df4a/docs/admin/program_modules.rst) is useful if you want to know what one specific module does, but for admins creating a new program, it's a lot to ask them to read through the whole thing (and fill in the gaps or read more recent documentation/updates) before just checking off the minimum number of modules for a program.

If I may propose an organization scheme, I think there needs to be a short documentation of modules with respect to each of three properties:
* the module is required for the program to run (such as TeacherClassRegModule) or worse, is required for the site to even accept your program (I'm not sure which these are -- and correct me if they don't exist, but they seem to be there... I can investigate further if it makes a difference to anyone.)
* the module requires another module in order to do its job (many modules, like volunteer reg, are pretty useless without their corresponding management module); this category is only really a useful subdivision of the modules that are optional (as opposed to the previous bullet)
* the module has a corresponding this-or-that module. Sadly for my brain, there are some of these in both the required variety (such as one of the two student reg modules: lottery versus first-come-first-served) and the optional variety (things like the CyberSource vs. Stripe credit card payment modules, where it is fine to select one or neither, but not both). In short, there needs to be a list of modules that do not play nicely with each other.

Alternatively, in lieu of admin-facing documentation, it may make sense to hide the required modules (and the ones that might as well be required) from admins entirely and make them automatically selected whenever a new program is created, turn the this-or-that required modules into radio buttons where admins can select (for instance) a lottery program or a FCFS program, and then let the remaining (truly optional) ones be check-box/select from a list, ideally with some kind of built-in features (or at least a JS warning) that would force admins to select as a group modules that go together and not select multiple modules that clash with one another. Thoughts?

Complete aside: the warning that it is very hard to undo selections made in program creation seems to be less relevant than when it was originally put there. Is there a reason we still keep such a strong warning there, or is that a vestige of the Userbits days?

**Comment by mgersh** [comment]
I've had partial work on something fairly similar to what you're suggesting sitting around for ages, which is why I'm marked as "assigned" both here and #220. One of these days I'll get around to finishing it.

Things it does or is planned to do once I finish:
- Frontend for choosing modules, both as part of program creation (this is the only part that I didn't finish, although the rest of it probably has bit rot by now) and accessible later
- Marks some program modules as always enabled and some as depending on others, so they don't show up in the frontend's list

Things it doesn't do:
- Handle either-or situations. I haven't seen this cause problems in practice, but maybe you have? The two-phase lottery is normally used together with the student classreg module, and the old lottery module claims that it clashes with the student classreg module but I don't know whether that's true or if it even still works; I don't think anyone has used it since before my time.

I agree that the warning is useless--it's still true for the program name itself, but not for any of the other stuff, and the other stuff is what that page looks like it wants you to check.

**Comment by milescalabresi** [comment]
Awesome! No, I haven't heard of the either-or thing being a big issue, but it seems sort of unsatisfying to build in all the other dependencies but do nothing about modules that can't both be selected. If it's not worth the effort to build it into the selection process, I might try to put together a written warning with a list of modules that don't work well together. I think it would be nice for the user to know why something broke or the program didn't get created.

**Comment by milescalabresi** [comment]
![](https://i.ytimg.com/vi/IPwxLw68Gys/maxresdefault.jpg)


https://docs.google.com/document/d/15tyEQ3cxJ4UCjm7EHgxFZx1j2Tl6TS7dZlCEMY34g9M/edit#heading=h.lqebjo4ktiy4

As a band-aid I can link to that page in my new prose-fixing PR (english-fixes). I will aim to make a full PR later with a more complete solution as described here
