### ISSUE TITLE
Grade ranges for individual sections

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#839]
Clark has requested that teachers be able to specify different grade ranges for different sections of a class so that they don't have to register the class multiple times.  For example, you could teach one section for high schoolers and one for middle schoolers.

**Comment by milescalabresi** [comment]
Probably makes the most sense to make two subjects. As @willgearty has pointed out, it is quite easy to import the subject you just registered but change the grade (probably just as easy as any section-level mechanism we would implement). However, there is room for improvement: the import text is confusing since it says "teach a class from a previous program." So let's improve that and if the issue is brought up again, we can recommend this easy process as the preferred way to do what the teacher is asking for.
